sudo: false
language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
script:
    - go test -coverprofile=app.coverprofile ./app
    - go test -coverprofile=middleware.coverprofile ./middleware
    - go test -coverprofile=rest.coverprofile ./rest
    - $HOME/gopath/bin/gover
    # - "$HOME/gopath/bin/goveralls
    #   -service=travis-ci
    #   -coverprofile=gover.coverprofile
    #   -repotoken=$COVERALLS_TOKEN"
