swagger: '2.0'
info:
  title: Comodoro API
  description: Command fleets of containers.
  version: "0.1.0"
host: localhost:8000
schemes:
  - http
basePath: /api
produces:
  - application/json
paths:
  /fleet/units:
    post:
      summary: Fleet units
      description: Submit a new fleet unit.
      tags:
        - fleet
      parameters:
        - name: unit
          in: body
          description: Unit to add to fleet
          required: true
          schema:
            $ref: '#/definitions/Unit'
      responses:
        201:
          description: The created unit
          schema:
            $ref: '#/definitions/Unit'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        409:
          description: Duplicate unit
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    get:
      summary: Fleet units
      description: |
        Get a collection of all fleet units.
      tags:
        - fleet
      responses:
        200:
          description: An array of fleet units
          schema:
            type: array
            items:
              $ref: '#/definitions/Unit'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /fleet/units/{name}:
    get:
      description: Get a fleet unit by ID.
      parameters:
        - name: name
          in: path
          description: Name of unit to fetch
          required: true
          type: string
      responses:
        200:
          description: Fleet unit
          schema:
            $ref: '#/definitions/Unit'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: Delete a fleet unit by name.
      parameters:
        - name: name
          in: path
          description: Name of unit to delete
          required: true
          type: string
      responses:
        204:
          description: Successfully deleted
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Unit:
    type: object
    properties:
      name:
        type: string
        description: Fleet unit name.
      body:
        type: object
        description: Fleet unit body.
        additionalProperties:
          type: string
  Error:
    type: string
    description: Error message
